version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
      - "28017:28017"
  # Requires `make build` as this only packages static files
  reactjs:
    image: banjocat/outage_reactjs
    build: ./reactjs/.
    volumes:
      - './reactjs/nginx.conf:/etc/nginx/conf.d/default.conf'
    environment:
      EXPRESS_HOST: "express:3000"
    ports:
      - "3000:80"
    depends_on:
      - express
  express:
    image: banjocat/outage_express
    build: ./express/.
    volumes:
      - "./express/:/app/"
    environment:
      mongo_url: mongodb
      express_port: 3000
    ports:
      - "3001:3000"
    depends_on:
      - mongodb


  

