version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
      - "28017:28017"
  # Requires `make build` as this only packages static files
  reactjs:
    build:
      context: ./reactjs
      dockerfile: Dockerfile-dev
    volumes:
      - "./reactjs/src:/app/src"
      - "./reactjs/public:/app/public"
    ports:
      - "3000:3000"
    depends_on:
      - express
  express:
    build: ./express/.
    volumes:
      - "./express/:/app/"
    environment:
      mongo_url: mongodb
      express_port: 4000
      reactjs_url: http://localhost:3000

    ports:
      - "4000:4000"
    depends_on:
      - mongodb


  

